### ISSUE TITLE
`hx start --dev` does not provide console output or serve static files

### ISSUE THREAD

**Issue by parthjoshi2007** [hendrix/hendrix#154]
Hi,

I heard about `hendrix` recently and was hugely excited. I've been using `scrapy` for my web scraping needs which is based on Twisted and I thought this would be the perfect solution to write a web UI around it customized to my requirements. Also the idea of not using celery where it is not required greatly appealed to me. So long story short, I installed `hendrix` yesterday to start playing around with it but was a little disappointed that what seemed simple in the documentation did not work too well in practice.

First off, I installed the latest version of `django` (2.1.2) on an Ubuntu 18.04 machine in a Python 3.6 virtualenv. Here, the command `hx start` fails to detect the django settings because, of all reasons, the double quotes have been replaced by single quotes in the `manage.py` file! Why the regex for discovering the Django settings module does not look for the term `DJANGO_SETTINGS_MODULE` but a double quoted string is beyond me. Maybe I'm missing something here. Anyways, this bug was trivial enough to fix. I'd be happy to raise a PR to fix the regex, if you guys think it is relevant.

After this, I ran `hx start` and it worked! But even with `--loud` and `-v 3` there was no console output. I tried running `hx start --dev --loud -v 3` and still nada. Specifying a log file with `--log` also produced no output either on the console or in the log file. I also verified that `--reload` was working as advertised but even when the server restarts there is no console output. Till now, I was testing the server with curl. I decided to test things in the browser and lo and behold, I got my first entries on the console, saying

```
Not Found: /static/rest_framework/css/bootstrap.min.css
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
Not Found: /static/rest_framework/css/prettify.css
Not Found: /static/rest_framework/js/csrf.js
......
```
I would assume that like Django's dev server, `hendrix start` would take care of serving static files. The `hendrix` [documentation](https://hendrix.readthedocs.io/en/latest/static_files/) is silent on the matter.

I'd really really appreciate if someone could tell me what I'm doing wrong or point me in the right direction (I'm pretty much a noob to async programming in general and the Twisted environment in particular). I'd be happy to provide more details about my environment or any other questions about my setup. I've been banging my head on this for a day and the fact that it's almost, so nearly working but not quite is getting to me. :(

**Comment by jmgamboa** [comment]
hi @parthjoshi2007 recently did a writeup on stack about staticfiles so this caught my attention. did you properly configure static files the django way? have a look [here](https://stackoverflow.com/questions/52560619/404-error-for-django-serving-static-files-how-to-setup-django-to-serve-static-f/52560826#52560826) and make sure you have checked off all the points.

**Comment by parthjoshi2007** [comment]
Thanks @jmgamboa. Static file serving taken care of. Shouldn't have missed this. I kept comparing it to Django's dev server and thought there was something missing. Any ideas on the no console output issue as well?

**Comment by parthjoshi2007** [comment]
Oh is that so? I'll try with Python 3.3 and revert back. Can you please provide me a link to the corresponding Twisted documentation. Thanks.

**Comment by jmgamboa** [comment]
i was just having a look at this. https://twistedmatrix.com/documents/14.0.2/core/howto/python3.html. worded "currently being ported" so that may mean its not even supported.

**Comment by parthjoshi2007** [comment]
Hey, I just installed Python3.3 and the error I get when install Twisted is 
```shell
Collecting Twisted>=13.1.0 (from scrapy->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/90/50/4c315ce5d119f67189d1819629cae7908ca0b0a6c572980df5cc6942bc22/Twisted-18.7.0.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-os_wft/Twisted/setup.py", line 20, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "<string>", line 212, in getSetupArgs
      File "<string>", line 202, in _checkPythonVersion
    ImportError: Twisted on Python 3 requires Python 3.4 or later.
```
It seems Twisted is not only ported (as this [link](http://py3readiness.org/) shows) but since Python3.3 has reached EOL, it requres a version later than 3.4. Will try with Python3.4 now. But I doubt that the Python version is the issue now. Probably has something to do with the Chalk library which is what hendrix uses to write pretty messages to the console. Scrapy has no problems running on top of Twisted on my machine.

**Comment by parthjoshi2007** [comment]
I tried with Python3.4 also and no difference.

**Comment by parthjoshi2007** [comment]
As I guessed, the issue has to do with `pychalk`, specifically its latest major version bump to 2.0.0. Downgrading `pychalk` to `1.1.0` with `pip install pychalk==1.1.0` did the trick. Now at least I see `hendrix` output what port it is listening on etc. Will update this space if any other issues come up
