### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by cancan101** [hendrix/hendrix#57]
I get this error when starting hx:

```
Traceback (most recent call last):
  File "/usr/local/bin/hx", line 7, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/hendrix/ux.py", line 181, in main
    options = djangoVsWsgi(options)
  File "/usr/local/lib/python2.7/dist-packages/hendrix/ux.py", line 119, in djangoVsWsgi
    settings_mod = findSettingsModule()
  File "/usr/local/lib/python2.7/dist-packages/hendrix/ux.py", line 104, in findSettingsModule
    r"([\"\'](?P<module>[a-z\.]+)[\"\'])", manage.read()
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by jMyles** [comment]
Where are we on this issue?
