### ISSUE TITLE
Setting 'workers' in the options kwarg without using hx causes error

### ISSUE THREAD

**Issue by jMyles** [hendrix/hendrix#95]
If you try to launch multiple workers by passing an options dict with a "workers" key, the HendrixService itself attempts to call hx:

```
Upon execvpe hx ['hx', 'start', '--http_port', '8000', '--https_port', '4430', '--cache_port', '8080', '--workers', '0', '--fd', "(dp0\nS'main_web_tcp'\np1\nI3\ns.", '--wsgi', 'Router'] in environment id 139949974285960
:Traceback (most recent call last):
  File "/home/justin/.virtualenvs/hendrix_dev/local/lib/python2.7/site-packages/twisted/internet/process.py", line 424, in _fork
    environment)
  File "/home/justin/.virtualenvs/hendrix_dev/local/lib/python2.7/site-packages/twisted/internet/process.py", line 502, in _execChild
    os.execvpe(executable, args, environment)
  File "/home/justin/.virtualenvs/hendrix_dev/lib/python2.7/os.py", line 355, in execvpe
    _execvpe(file, args, env)
  File "/home/justin/.virtualenvs/hendrix_dev/lib/python2.7/os.py", line 382, in _execvpe
    _execvpe(file, args, env)
    func(fullname, *argrest)
  File "/home/justin/.virtualenvs/hendrix_dev/lib/python2.7/os.py", line 382, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
```

**Comment by JamesTFarrington** [comment]
This line looks guilty.

https://github.com/hendrix/hendrix/blob/master/hendrix/deploy/base.py#L223

**Comment by jMyles** [comment]
Agreed.  GUILTY!

**Comment by JamesTFarrington** [comment]
I think we have another suspect

https://github.com/hendrix/hendrix/blob/master/hendrix/ux.py#L215

**Comment by JamesTFarrington** [comment]
https://github.com/hendrix/hendrix/blob/argparse/hendrix/ux.py#L35
